//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateWithBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public System.DateTime post_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> views { get; set; }
        public int image_id { get; set; }
        public Nullable<int> comment_id { get; set; }
    
        public virtual File File { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
